### PR TITLE
fix typo in Dockerfile.gpu

### PR DESCRIPTION
**Pull request by takov751**
Nothing invasive, just saw path typo in sed command

### CODE REVIEW

**Comment by krisgesling** [comment]
Thanks for this - I'll let Mike confirm the fix, but wanted to let you know about our Contributor Licensing Agreement (CLA).

I know it may seem like a small contribution however to protect yourself, the project, and users of Mycroft technologies we require a Contributor Licensing Agreement (CLA) before accepting any contributions to a Mycroft repository. This agreement makes it crystal clear that along with your code you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license.

It might seem overkill on small PR's like this one, however it greatly simplifies our processes to have a blanket rule for all contributions. I hope you understand.

On the plus side - you will also be added to [our list of excellent human beings](https://github.com/MycroftAI/contributors)!

Please visit https://mycroft.ai/cla to initiate this one-time signing.

Thank you!

**Comment by takov751** [comment]
I've done it. Indeed slightly overkill, however from a legal POV perfectly reasonable. :+1:

**Comment by krisgesling** [comment]
Thanks for understanding - CLA received :+1:

**Comment by synesthesiam** [comment]
Thank you!

**Pull request merged**
